//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.3.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;
using NetTopologySuite.Geometries;

namespace BackendModel
{
   /// <summary>
   /// Manager of the CornellGO data
   /// </summary>
   [System.ComponentModel.Description("Manager of the CornellGO data")]
   public partial class Admin
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Admin()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Admin CreateAdminUnsafe()
      {
         return new Admin();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="email">Email of the admin</param>
      /// <param name="passwordhash">Password of the admin</param>
      /// <param name="status">Status of the account</param>
      /// <param name="signalrid">The SignalR id for the current session of this admin</param>
      public Admin(string email, string passwordhash, global::BackendModel.AdminAccountStatus status, string signalrid)
      {
         if (string.IsNullOrEmpty(email)) throw new ArgumentNullException(nameof(email));
         this.Email = email;

         if (string.IsNullOrEmpty(passwordhash)) throw new ArgumentNullException(nameof(passwordhash));
         this.PasswordHash = passwordhash;

         this.Status = status;

         if (string.IsNullOrEmpty(signalrid)) throw new ArgumentNullException(nameof(signalrid));
         this.SignalRId = signalrid;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="email">Email of the admin</param>
      /// <param name="passwordhash">Password of the admin</param>
      /// <param name="status">Status of the account</param>
      /// <param name="signalrid">The SignalR id for the current session of this admin</param>
      public static Admin Create(string email, string passwordhash, global::BackendModel.AdminAccountStatus status, string signalrid)
      {
         return new Admin(email, passwordhash, status, signalrid);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// Email of the admin
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Email of the admin")]
      public string Email { get; set; }

      /// <summary>
      /// Required
      /// Password of the admin
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Password of the admin")]
      public string PasswordHash { get; set; }

      /// <summary>
      /// Required
      /// Status of the account
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Status of the account")]
      public global::BackendModel.AdminAccountStatus Status { get; set; }

      /// <summary>
      /// Required
      /// The SignalR id for the current session of this admin
      /// </summary>
      [Required]
      [System.ComponentModel.Description("The SignalR id for the current session of this admin")]
      public string SignalRId { get; set; }

   }
}

