//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.2.0
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;
using NetTopologySuite.Geometries;

namespace BackendModel
{
   /// <summary>
   /// User authentication data
   /// </summary>
   [System.ComponentModel.Description("User authentication data")]
   public partial class Authenticator
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected Authenticator()
      {
         User = global::BackendModel.User.CreateUserUnsafe();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static Authenticator CreateAuthenticatorUnsafe()
      {
         return new Authenticator();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="username">Username associated with the authenticator up to 60 chars</param>
      /// <param name="password">User&apos;s password hash</param>
      /// <param name="timestamp">Creation timestamp</param>
      public Authenticator(string username, string password, DateTime timestamp)
      {
         if (string.IsNullOrEmpty(username)) throw new ArgumentNullException(nameof(username));
         this.Username = username;

         if (string.IsNullOrEmpty(password)) throw new ArgumentNullException(nameof(password));
         this.Password = password;

         this.Timestamp = timestamp;


         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="username">Username associated with the authenticator up to 60 chars</param>
      /// <param name="password">User&apos;s password hash</param>
      /// <param name="timestamp">Creation timestamp</param>
      public static Authenticator Create(string username, string password, DateTime timestamp)
      {
         return new Authenticator(username, password, timestamp);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required, Min length = 1, Max length = 120
      /// Username associated with the authenticator up to 60 chars
      /// </summary>
      [Required]
      [MinLength(1)]
      [MaxLength(120)]
      [StringLength(120)]
      [System.ComponentModel.Description("Username associated with the authenticator up to 60 chars")]
      public string Username { get; set; }

      /// <summary>
      /// Required, Min length = 8
      /// User&apos;s password hash
      /// </summary>
      [Required]
      [MinLength(8)]
      [System.ComponentModel.Description("User's password hash")]
      public string Password { get; set; }

      /// <summary>
      /// Required
      /// Creation timestamp
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Creation timestamp")]
      public DateTime Timestamp { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required&lt;br/&gt;
      /// User that this is authenticating
      /// </summary>
      [Description("User that this is authenticating")]
      public virtual global::BackendModel.User User { get; set; }

   }
}

