//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.3.2
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;
using NetTopologySuite.Geometries;

namespace BackendModel
{
   /// <summary>
   /// Entry for the user&apos;s log
   /// </summary>
   [System.ComponentModel.Description("Entry for the user's log")]
   public partial class SessonLogEntry
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected SessonLogEntry()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static SessonLogEntry CreateSessonLogEntryUnsafe()
      {
         return new SessonLogEntry();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="entrytype">Type of entry</param>
      /// <param name="entrydata">If applicable, semicolon separated list of strings/numbers relating to this entry (no spaces other than those required by the strings themselves).</param>
      /// <param name="timestamp">Time that this entry was created</param>
      /// <param name="_user0"></param>
      public SessonLogEntry(global::BackendModel.SessionLogEntryType entrytype, string entrydata, DateTime timestamp, global::BackendModel.User _user0)
      {
         this.EntryType = entrytype;

         if (string.IsNullOrEmpty(entrydata)) throw new ArgumentNullException(nameof(entrydata));
         this.EntryData = entrydata;

         this.Timestamp = timestamp;

         if (_user0 == null) throw new ArgumentNullException(nameof(_user0));
         _user0.SessonLogEntries.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="entrytype">Type of entry</param>
      /// <param name="entrydata">If applicable, semicolon separated list of strings/numbers relating to this entry (no spaces other than those required by the strings themselves).</param>
      /// <param name="timestamp">Time that this entry was created</param>
      /// <param name="_user0"></param>
      public static SessonLogEntry Create(global::BackendModel.SessionLogEntryType entrytype, string entrydata, DateTime timestamp, global::BackendModel.User _user0)
      {
         return new SessonLogEntry(entrytype, entrydata, timestamp, _user0);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// Type of entry
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Type of entry")]
      public global::BackendModel.SessionLogEntryType EntryType { get; set; }

      /// <summary>
      /// Required
      /// If applicable, semicolon separated list of strings/numbers relating to this entry
      /// (no spaces other than those required by the strings themselves).
      /// </summary>
      [Required]
      [System.ComponentModel.Description("If applicable, semicolon separated list of strings/numbers relating to this entry (no spaces other than those required by the strings themselves).")]
      public string EntryData { get; set; }

      /// <summary>
      /// Required
      /// Time that this entry was created
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Time that this entry was created")]
      public DateTime Timestamp { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

   }
}

