//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BackendModel
{
   /// <summary>
   /// Type of entry in session log
   /// </summary>
   [System.ComponentModel.Description("Type of entry in session log")]
   public enum SessionLogEntryType : Int32
   {
      /// <summary>
      /// User was created
      /// </summary>
      [System.ComponentModel.Description("User was created")]
      UserCreated,
      /// <summary>
      /// User logged in
      /// </summary>
      [System.ComponentModel.Description("User logged in")]
      Login,
      /// <summary>
      /// User logged out
      /// </summary>
      [System.ComponentModel.Description("User logged out")]
      Logout,
      /// <summary>
      /// User used session token to login again
      /// </summary>
      [System.ComponentModel.Description("User used session token to login again")]
      Relog,
      /// <summary>
      /// User lost connection or app crashed
      /// </summary>
      [System.ComponentModel.Description("User lost connection or app crashed")]
      LostConnection,
      /// <summary>
      /// App was closed 
      /// </summary>
      [System.ComponentModel.Description("App was closed ")]
      ClosedApp,
      /// <summary>
      /// App was suspended by the OS
      /// </summary>
      [System.ComponentModel.Description("App was suspended by the OS")]
      AppSuspended,
      /// <summary>
      /// User found place with id X
      /// </summary>
      [System.ComponentModel.Description("User found place with id X")]
      FoundPlace,
      /// <summary>
      /// User joined a group with N people
      /// </summary>
      [System.ComponentModel.Description("User joined a group with N people")]
      JoinGroup,
      /// <summary>
      /// User joined group this person is a part of
      /// </summary>
      [System.ComponentModel.Description("User joined group this person is a part of")]
      UserFromGroupJoined,
      /// <summary>
      /// User left group this person is a part of
      /// </summary>
      [System.ComponentModel.Description("User left group this person is a part of")]
      UserFromGroupLeft,
      /// <summary>
      /// User left group
      /// </summary>
      [System.ComponentModel.Description("User left group")]
      LeaveGroup,
      /// <summary>
      /// User opened the leaderboard menu
      /// </summary>
      [System.ComponentModel.Description("User opened the leaderboard menu")]
      OpenLeaderboard,
      /// <summary>
      /// User opened the history menu
      /// </summary>
      [System.ComponentModel.Description("User opened the history menu")]
      OpenHistory,
      /// <summary>
      /// User opened the learn more menu
      /// </summary>
      [System.ComponentModel.Description("User opened the learn more menu")]
      OpenLearnMore,
      /// <summary>
      /// User changed avatar from url X to url Y
      /// </summary>
      [System.ComponentModel.Description("User changed avatar from url X to url Y")]
      ChangeAvatar,
      /// <summary>
      /// User changed username to X
      /// </summary>
      [System.ComponentModel.Description("User changed username to X")]
      ChangeUsername,
      /// <summary>
      /// User opened the group menu
      /// </summary>
      [System.ComponentModel.Description("User opened the group menu")]
      OpenGroupMenu,
      /// <summary>
      /// User kicked a member
      /// </summary>
      [System.ComponentModel.Description("User kicked a member")]
      KickedMember,
      /// <summary>
      /// User disbanded a group
      /// </summary>
      [System.ComponentModel.Description("User disbanded a group")]
      DisbandedGroup,
      /// <summary>
      /// User opened the join group menu
      /// </summary>
      [System.ComponentModel.Description("User opened the join group menu")]
      OpenJoinGroupMenu,
      /// <summary>
      /// User returned to game menu
      /// </summary>
      [System.ComponentModel.Description("User returned to game menu")]
      OpenGameMenu,
      /// <summary>
      /// User was kicked by host
      /// </summary>
      [System.ComponentModel.Description("User was kicked by host")]
      KickedByHost,
      /// <summary>
      /// Occurs when user accesses settings button.
      /// </summary>
      [System.ComponentModel.Description("Occurs when user accesses settings button.")]
      OpenSettings,
      /// <summary>
      /// Occurs when app is restored from the background.
      /// </summary>
      [System.ComponentModel.Description("Occurs when app is restored from the background.")]
      AppResumed
   }
}
