//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.2.0
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;
using NetTopologySuite.Geometries;

namespace BackendModel
{
   /// <summary>
   /// A user&apos;s session with the server
   /// </summary>
   [System.ComponentModel.Description("A user's session with the server")]
   public partial class UserSession
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected UserSession()
      {
         User = global::BackendModel.User.CreateUserUnsafe();

         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static UserSession CreateUserSessionUnsafe()
      {
         return new UserSession();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="timestamp">Creation timestamp</param>
      /// <param name="user"></param>
      public UserSession(DateTime timestamp, global::BackendModel.User user)
      {
         this.Timestamp = timestamp;

         if (user == null) throw new ArgumentNullException(nameof(user));
         this.User = user;


         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="timestamp">Creation timestamp</param>
      /// <param name="user"></param>
      public static UserSession Create(DateTime timestamp, global::BackendModel.User user)
      {
         return new UserSession(timestamp, user);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public long Id { get; set; }

      /// <summary>
      /// Required
      /// Creation timestamp
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Creation timestamp")]
      public DateTime Timestamp { get; set; }

      /// <summary>
      /// SignalR id tied to this user session
      /// </summary>
      [System.ComponentModel.Description("SignalR id tied to this user session")]
      public string SignalRId { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required&lt;br/&gt;
      /// User session tied to user
      /// </summary>
      [Description("User session tied to user")]
      public virtual global::BackendModel.User User { get; set; }

   }
}

